// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAws1R4ZEerFcMn4MjqinF2m5Vg6Qd_6Ts',
    appId: '1:868521258400:web:f517ff0995c01f693b08c5',
    messagingSenderId: '868521258400',
    projectId: 'leigha-bq-dev',
    authDomain: 'leigha-bq-dev.firebaseapp.com',
    storageBucket: 'leigha-bq-dev.appspot.com',
    measurementId: 'G-YZH3VMJGKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEVralpXenCQEOGnxoMMddEisyilx42zI',
    appId: '1:868521258400:android:2f26adace751c92c3b08c5',
    messagingSenderId: '868521258400',
    projectId: 'leigha-bq-dev',
    storageBucket: 'leigha-bq-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPbqB1-0AFnvZIwsj_i9emIRqGhKqITXM',
    appId: '1:868521258400:ios:b40ac311bc5fdee33b08c5',
    messagingSenderId: '868521258400',
    projectId: 'leigha-bq-dev',
    storageBucket: 'leigha-bq-dev.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPbqB1-0AFnvZIwsj_i9emIRqGhKqITXM',
    appId: '1:868521258400:ios:b40ac311bc5fdee33b08c5',
    messagingSenderId: '868521258400',
    projectId: 'leigha-bq-dev',
    storageBucket: 'leigha-bq-dev.appspot.com',
    iosBundleId: 'com.example.myApp',
  );
}
